title: Data.gouv.fr Docs
description: >
    La documentation du site data.gouv.fr

twitter_username: etalab
github_username:  etalab

github_repository: etalab/doc.data.gouv.fr

url: https://doc.data.gouv.fr

lang: fr
permalink: pretty

i18n:
  en:
    edit: Edit this page
  fr:
    edit: Editer cette page

sass:
    style: compressed


exclude:
  - README.md
  - docker-compose.yml
  - circle.yml
  - deploy
  - Gemfile
  - Gemfile.lock
  - vendor


collections:
  faq:
    title: DÃ©couvrir l'OpenData
    output: true
    order: 1
  api:
    title: API
    output: true
    order: 2



defaults:
  - scope:
      path: ""
    values:
      layout: page

theme: jekyll-theme-gouvfr
